apiVersion: v1
kind: Service
metadata:
  name: lumina-backend-service
  labels:
    app: lumina-backend
spec:
  type: ClusterIP          # This allows internal access only
  selector:
    app: lumina-backend          # Must match your Deployment labels
  ports:
    - protocol: TCP
      port: 4000           # Internal Cluster Port
      targetPort: 4000  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumina-backend-deployment
  labels:
    app: lumina-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumina-backend
  template:
    metadata:
      labels:
        app: lumina-backend
    spec:
      containers:
      - name: lumina-backend
        image: nyeinchan312/lumina-backend:latest
        ports:
        - containerPort: 4000
        env:
          - name: DB_HOST
            value: "host.docker.internal"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "coredb"
          - name: DB_USER
            value: "admin"
          - name: DB_PASSWORD
            value: "password123"