apiVersion: v1
kind: Service
metadata:
  name: lumina-frontend-service
  labels:
    app: lumina-frontend
spec:
  type: ClusterIP          # This allows internal access only
  selector:
    app: lumina-frontend          # Must match your Deployment labels
  ports:
    - protocol: TCP
      port: 80           # Internal Cluster Port
      targetPort: 80  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumina-frontend-deployment
  labels:
    app: lumina-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumina-frontend
  template:
    metadata:
      labels:
        app: lumina-frontend
    spec:
      containers:
      - name: lumina-frontend
        image: nyeinchan312/lumina-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://lumina-backend-service:4000"