apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lumina-backend-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=nyeinchan312/lumina-backend:dev
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.pull-secret: pullsecret:argocd/dockerhub-creds
spec:
  project: default
  source:
    repoURL: https://github.com/nyeinchan4/lumina.git
    targetRevision: develop
    path: K8s/overlays/dev/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: lumina-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
