apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lumina-frontend-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=nyeinchan312/lumina-frontend:dev
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:argocd/dockerhub-creds
spec:
  project: default
  source:
    repoURL: https://github.com/nyeinchan4/lumina.git
    targetRevision: master
    path: K8s/overlays/dev/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: lumina-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
