apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lumina-frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=<your-dockerhub-username>/lumina-frontend:dev
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:argocd/dockerhub-creds
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/<your-repo>.git
    targetRevision: main
    path: K8s/base/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
